# Generated by Django 6.0.5 on 2026-05-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('doctor_id', models.IntegerField()),
                ('speciality', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
    ]
